version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    depends_on:
      - redis
    volumes:
      - ./app:/app/app

  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    volumes:
    - grafana_data:/var/lib/grafana
    - ./grafana/provisioning:/etc/grafana/provisioning
    - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this password in production
    - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
    - prometheus
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_ENDPOINT=http://app:8000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - app

volumes:
  redis_data:
  grafana_data: