services:
  - type: web
    name: codesage-api
    env: docker
    plan: free
    dockerfilePath: Dockerfile.api
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: REDIS_HOST
        fromService:
          name: codesage-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: codesage-redis
          type: redis
          property: port

  - type: web
    name: codesage-streamlit
    env: docker
    dockerfilePath: Dockerfile.streamlit
    plan: free
    envVars:
      - key: API_ENDPOINT
        value: https://codesage-api.onrender.com
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8501

  - type: redis
    name: codesage-redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free

  - type: web
    name: codesage-grafana
    env: docker
    plan: free
    dockerCommand: grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini
    envVars:
      - key: GF_SECURITY_ADMIN_PASSWORD
        sync: false
      - key: GF_INSTALL_PLUGINS
        value: grafana-piechart-panel
      - key: GF_SERVER_ROOT_URL
        value: https://codesage-grafana.onrender.com
      - key: GF_SECURITY_ALLOW_EMBEDDING
        value: true
      - key: GF_AUTH_ANONYMOUS_ENABLED
        value: true
      - key: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
        value: /var/lib/grafana/dashboards/dashboard.json
    healthCheckPath: /api/health
    disk:
      name: grafana-data
      mountPath: /var/lib/grafana
      sizeGB: 1